# 端口
server:
  port: 18080

# MybatisPlus 配置
mybatis-plus:
  ## SQL 打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      ## 逻辑删除字段
      logic-delete-field: deleted
      ## 已删除值
      logic-delete-value: 0
      ## 未删除值
      logic-not-delete-value: 1
  ## xml 文件扫描路径
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml

# ShardingSphere 配置
spring:
  shardingsphere:
    ## 数据源配置
    datasource:
      names: ds,ds0,ds1
      ds:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ds?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: root
        password: root
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ds0?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: root
        password: root
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ds1?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: root
        password: root
    ## 开启 SQL 打印
    props:
      sql:
        show: true
    sharding:
      ## 默认数据源
      default-data-source-name: ds
      ## 数据库分片策略，按 ID 字段取模
      default-database-strategy:
        inline:
          algorithm-expression: ds$->{id % 2}
          sharding-column: id
      tables:
        tab_user:
          actual-data-nodes: ds$->{0..1}.tab_user$->{0..1}
          ## 表分片策略，ID 字段取模，按 age 字段取模
          table-strategy:
            inline:
              algorithm-expression: tab_user$->{age % 2}
              sharding-column: age