# 端口
server:
  port: 18080

# MybatisPlus 配置
mybatis-plus:
  ## SQL 打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      ## 逻辑删除字段
      logic-delete-field: deleted
      ## 已删除值
      logic-delete-value: 1
      ## 未删除值
      logic-not-delete-value: 0
  ## xml 文件扫描路径
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml

# ShardingSphere 配置
spring:
  shardingsphere:
    ## 数据源配置
    datasource:
      names: ds,ds0,ds1
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: root
        password: root
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowMultiQueries=true
        username: root
        password: root
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: id
            sharding-algorithm-name: database-inline
        binding-tables:
          - tab_user
        tables:
          tab_user:
            actual-data-nodes: ds$->{0..1}.tab_user$->{0..1}
            table-strategy:
              standard:
                sharding-column: age
                sharding-algorithm-name: tab_user-inline
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{id % 2}
          tab_user-inline:
            type: INLINE
            props:
              algorithm-expression: tab_user$->{age % 2}
    mode:
      type: Memory
    props:
      sql-show: true